print("Hello World!")
print("99 bottles of root beer on the wall, 99 bottles of root beer.")
print("Take one down and pass it around, 98 bottles of root beer on the wall.")
print("98 bottles of root beer on the wall, 98 bottles of root beer.")
print("Take one down and pass it around, 97 bottles of root beer on the wall.")
print("97 bottles of root beer on the wall, 97 bottles of root beer.")
print("Take one down and pass it around, 96 bottles of root beer on the wall.")
print("96 bottles of root beer on the wall, 96 bottles of root beer.")
print("Take one down and pass it around, 95 bottles of root beer on the wall.")
print("95 bottles of root beer on the wall, 95 bottles of root beer.")
print("Take one down and pass it around, 94 bottles of root beer on the wall.")
print("94 bottles of root beer on the wall, 94 bottles of root beer.")
print("Take one down and pass it around, 93 bottles of root beer on the wall.")
print("93 bottles of root beer on the wall, 93 bottles of root beer.")
print("Take one down and pass it around, 92 bottles of root beer on the wall.")
print("92 bottles of root beer on the wall, 92 bottles of root beer.")
print("Take one down and pass it around, 91 bottles of root beer on the wall.")
print("91 bottles of root beer on the wall, 91 bottles of root beer.")
print("Take one down and pass it around, 90 bottles of root beer on the wall.")
print("90 bottles of root beer on the wall, 90 bottles of root beer.")
print("Take one down and pass it around, 89 bottles of root beer on the wall.")
print("89 bottles of root beer on the wall, 89 bottles of root beer.")
print("Take one down and pass it around, 88 bottles of root beer on the wall.")
print("88 bottles of root beer on the wall, 88 bottles of root beer.")
print("Take one down and pass it around, 87 bottles of root beer on the wall.")
print("87 bottles of root beer on the wall, 87 bottles of root beer.")
print("Take one down and pass it around, 86 bottles of root beer on the wall.")
print("86 bottles of root beer on the wall, 86 bottles of root beer.")
print("Take one down and pass it around, 85 bottles of root beer on the wall.")
print("85 bottles of root beer on the wall, 85 bottles of root beer.")
print("Take one down and pass it around, 84 bottles of root beer on the wall.")
print("84 bottles of root beer on the wall, 84 bottles of root beer.")
print("Take one down and pass it around, 83 bottles of root beer on the wall.")
print("83 bottles of root beer on the wall, 83 bottles of root beer.")
print("Take one down and pass it around, 82 bottles of root beer on the wall.")
print("82 bottles of root beer on the wall, 82 bottles of root beer.")
print("Take one down and pass it around, 81 bottles of root beer on the wall.")
print("81 bottles of root beer on the wall, 81 bottles of root beer.")
print("Take one down and pass it around, 80 bottles of root beer on the wall.")
print("80 bottles of root beer on the wall, 80 bottles of root beer.")
print("Take one down and pass it around, 79 bottles of root beer on the wall.")
print("79 bottles of root beer on the wall, 79 bottles of root beer.")
print("Take one down and pass it around, 78 bottles of root beer on the wall.")
print("78 bottles of root beer on the wall, 78 bottles of root beer.")
print("Take one down and pass it around, 77 bottles of root beer on the wall.")
print("77 bottles of root beer on the wall, 77 bottles of root beer.")
print("Take one down and pass it around, 76 bottles of root beer on the wall.")
print("76 bottles of root beer on the wall, 76 bottles of root beer.")
print("Take one down and pass it around, 75 bottles of root beer on the wall.")
print("75 bottles of root beer on the wall, 75 bottles of root beer.")
print("Take one down and pass it around, 74 bottles of root beer on the wall.")
print("74 bottles of root beer on the wall, 74 bottles of root beer.")
print("Take one down and pass it around, 73 bottles of root beer on the wall.")
print("73 bottles of root beer on the wall, 73 bottles of root beer.")
print("Take one down and pass it around, 72 bottles of root beer on the wall.")
print("72 bottles of root beer on the wall, 72 bottles of root beer.")
print("Take one down and pass it around, 71 bottles of root beer on the wall.")
print("71 bottles of root beer on the wall, 71 bottles of root beer.")
print("Take one down and pass it around, 70 bottles of root beer on the wall.")
print("70 bottles of root beer on the wall, 70 bottles of root beer.")
print("Take one down and pass it around, 69 bottles of root beer on the wall.")
print("69 bottles of root beer on the wall, 69 bottles of root beer.")
print("Take one down and pass it around, 68 bottles of root beer on the wall.")
print("68 bottles of root beer on the wall, 68 bottles of root beer.")
print("Take one down and pass it around, 67 bottles of root beer on the wall.")
print("67 bottles of root beer on the wall, 67 bottles of root beer.")
print("Take one down and pass it around, 66 bottles of root beer on the wall.")
print("66 bottles of root beer on the wall, 66 bottles of root beer.")
print("Take one down and pass it around, 65 bottles of root beer on the wall.")
print("65 bottles of root beer on the wall, 65 bottles of root beer.")
print("Take one down and pass it around, 64 bottles of root beer on the wall.")
print("64 bottles of root beer on the wall, 64 bottles of root beer.")
print("Take one down and pass it around, 63 bottles of root beer on the wall.")
print("63 bottles of root beer on the wall, 63 bottles of root beer.")
print("Take one down and pass it around, 62 bottles of root beer on the wall.")
print("62 bottles of root beer on the wall, 62 bottles of root beer.")
print("Take one down and pass it around, 61 bottles of root beer on the wall.")
print("61 bottles of root beer on the wall, 61 bottles of root beer.")
print("Take one down and pass it around, 60 bottles of root beer on the wall.")
print("60 bottles of root beer on the wall, 60 bottles of root beer.")
print("Take one down and pass it around, 59 bottles of root beer on the wall.")
print("59 bottles of root beer on the wall, 59 bottles of root beer.")
print("Take one down and pass it around, 58 bottles of root beer on the wall.")
print("58 bottles of root beer on the wall, 58 bottles of root beer.")
print("Take one down and pass it around, 57 bottles of root beer on the wall.")
print("57 bottles of root beer on the wall, 57 bottles of root beer.")
print("Take one down and pass it around, 56 bottles of root beer on the wall.")
print("56 bottles of root beer on the wall, 56 bottles of root beer.")
print("Take one down and pass it around, 55 bottles of root beer on the wall.")
print("55 bottles of root beer on the wall, 55 bottles of root beer.")
print("Take one down and pass it around, 54 bottles of root beer on the wall.")
print("54 bottles of root beer on the wall, 54 bottles of root beer.")
print("Take one down and pass it around, 53 bottles of root beer on the wall.")
print("53 bottles of root beer on the wall, 53 bottles of root beer.")
print("Take one down and pass it around, 52 bottles of root beer on the wall.")
print("52 bottles of root beer on the wall, 52 bottles of root beer.")
print("Take one down and pass it around, 51 bottles of root beer on the wall.")
print("51 bottles of root beer on the wall, 51 bottles of root beer.")
print("Take one down and pass it around, 50 bottles of root beer on the wall.")
print("50 bottles of root beer on the wall, 50 bottles of root beer.")
print("Take one down and pass it around, 49 bottles of root beer on the wall.")
print("49 bottles of root beer on the wall, 49 bottles of root beer.")
print("Take one down and pass it around, 48 bottles of root beer on the wall.")
print("48 bottles of root beer on the wall, 48 bottles of root beer.")
print("Take one down and pass it around, 47 bottles of root beer on the wall.")
print("47 bottles of root beer on the wall, 47 bottles of root beer.")
print("Take one down and pass it around, 46 bottles of root beer on the wall.")
print("46 bottles of root beer on the wall, 46 bottles of root beer.")
print("Take one down and pass it around, 45 bottles of root beer on the wall.")
print("45 bottles of root beer on the wall, 45 bottles of root beer.")
print("Take one down and pass it around, 44 bottles of root beer on the wall.")
print("44 bottles of root beer on the wall, 44 bottles of root beer.")
print("Take one down and pass it around, 43 bottles of root beer on the wall.")
print("43 bottles of root beer on the wall, 43 bottles of root beer.")
print("Take one down and pass it around, 42 bottles of root beer on the wall.")
print("42 bottles of root beer on the wall, 42 bottles of root beer.")
print("Take one down and pass it around, 41 bottles of root beer on the wall.")
print("41 bottles of root beer on the wall, 41 bottles of root beer.")
print("Take one down and pass it around, 40 bottles of root beer on the wall.")
print("40 bottles of root beer on the wall, 40 bottles of root beer.")
print("Take one down and pass it around, 39 bottles of root beer on the wall.")
print("39 bottles of root beer on the wall, 39 bottles of root beer.")
print("Take one down and pass it around, 38 bottles of root beer on the wall.")
print("38 bottles of root beer on the wall, 38 bottles of root beer.")
print("Take one down and pass it around, 37 bottles of root beer on the wall.")
print("37 bottles of root beer on the wall, 37 bottles of root beer.")
print("Take one down and pass it around, 36 bottles of root beer on the wall.")
print("36 bottles of root beer on the wall, 36 bottles of root beer.")
print("Take one down and pass it around, 35 bottles of root beer on the wall.")
print("35 bottles of root beer on the wall, 35 bottles of root beer.")
print("Take one down and pass it around, 34 bottles of root beer on the wall.")
print("34 bottles of root beer on the wall, 34 bottles of root beer.")
print("Take one down and pass it around, 33 bottles of root beer on the wall.")
print("33 bottles of root beer on the wall, 33 bottles of root beer.")
print("Take one down and pass it around, 32 bottles of root beer on the wall.")
print("32 bottles of root beer on the wall, 32 bottles of root beer.")
print("Take one down and pass it around, 31 bottles of root beer on the wall.")
print("31 bottles of root beer on the wall, 31 bottles of root beer.")
print("Take one down and pass it around, 30 bottles of root beer on the wall.")
print("30 bottles of root beer on the wall, 30 bottles of root beer.")
print("Take one down and pass it around, 29 bottles of root beer on the wall.")
print("29 bottles of root beer on the wall, 29 bottles of root beer.")
print("Take one down and pass it around, 28 bottles of root beer on the wall.")
print("28 bottles of root beer on the wall, 28 bottles of root beer.")
print("Take one down and pass it around, 27 bottles of root beer on the wall.")
print("27 bottles of root beer on the wall, 27 bottles of root beer.")
print("Take one down and pass it around, 26 bottles of root beer on the wall.")
print("26 bottles of root beer on the wall, 26 bottles of root beer.")
print("Take one down and pass it around, 25 bottles of root beer on the wall.")
print("25 bottles of root beer on the wall, 25 bottles of root beer.")
print("Take one down and pass it around, 24 bottles of root beer on the wall.")
print("24 bottles of root beer on the wall, 24 bottles of root beer.")
print("Take one down and pass it around, 23 bottles of root beer on the wall.")
print("23 bottles of root beer on the wall, 23 bottles of root beer.")
print("Take one down and pass it around, 22 bottles of root beer on the wall.")
print("22 bottles of root beer on the wall, 22 bottles of root beer.")
print("Take one down and pass it around, 21 bottles of root beer on the wall.")
print("21 bottles of root beer on the wall, 21 bottles of root beer.")
print("Take one down and pass it around, 20 bottles of root beer on the wall.")
print("20 bottles of root beer on the wall, 20 bottles of root beer.")
print("Take one down and pass it around, 19 bottles of root beer on the wall.")
print("19 bottles of root beer on the wall, 19 bottles of root beer.")
print("Take one down and pass it around, 18 bottles of root beer on the wall.")
print("18 bottles of root beer on the wall, 18 bottles of root beer.")
print("Take one down and pass it around, 17 bottles of root beer on the wall.")
print("17 bottles of root beer on the wall, 17 bottles of root beer.")
print("Take one down and pass it around, 16 bottles of root beer on the wall.")
print("16 bottles of root beer on the wall, 16 bottles of root beer.")
print("Take one down and pass it around, 15 bottles of root beer on the wall.")
print("15 bottles of root beer on the wall, 15 bottles of root beer.")
print("Take one down and pass it around, 14 bottles of root beer on the wall.")
print("14 bottles of root beer on the wall, 14 bottles of root beer.")
print("Take one down and pass it around, 13 bottles of root beer on the wall.")
print("13 bottles of root beer on the wall, 13 bottles of root beer.")
print("Take one down and pass it around, 12 bottles of root beer on the wall.")
print("12 bottles of root beer on the wall, 12 bottles of root beer.")
print("Take one down and pass it around, 11 bottles of root beer on the wall.")
print("11 bottles of root beer on the wall, 11 bottles of root beer.")
print("Take one down and pass it around, 10 bottles of root beer on the wall.")
print("10 bottles of root beer on the wall, 10 bottles of root beer.")
print("Take one down and pass it around, 9 bottles of root beer on the wall.")
print("9 bottles of root beer on the wall, 9 bottles of root beer.")
print("Take one down and pass it around, 8 bottles of root beer on the wall.")
print("8 bottles of root beer on the wall, 8 bottles of root beer.")
print("Take one down and pass it around, 7 bottles of root beer on the wall.")
print("7 bottles of root beer on the wall, 7 bottles of root beer.")
print("Take one down and pass it around, 6 bottles of root beer on the wall.")
print("6 bottles of root beer on the wall, 6 bottles of root beer.")
print("Take one down and pass it around, 5 bottles of root beer on the wall.")
print("5 bottles of root beer on the wall, 5 bottles of root beer.")
print("Take one down and pass it around, 4 bottles of root beer on the wall.")
print("4 bottles of root beer on the wall, 4 bottles of root beer.")
print("Take one down and pass it around, 3 bottles of root beer on the wall.")
print("3 bottles of root beer on the wall, 3 bottles of root beer.")
print("Take one down and pass it around, 2 bottles of root beer on the wall.")
print("2 bottles of root beer on the wall, 2 bottles of root beer.")
print("Take one down and pass it around, 1 bottle of root beer on the wall.")
print("1 bottle of root beer on the wall, 1 bottle of root beer.")
print("Take one down and pass it around, no more bottles of root beer on the wall.")